---

- name: Install chrony
  ansible.builtin.package:
    name: "{{ chrony_packages }}"
    state: present

- name: Start chrony
  ansible.builtin.service:
    name: "{{ chrony_service }}"
    state: started
    enabled: yes
