---

- name: Install chrony
  ansible.builtin.package:
    name: "{{ chrony_packages }}"
    state: present

- name: Start chrony  # noqa ignore-errors
  ansible.builtin.service:
    name: "{{ chrony_service }}"
    state: started
    enabled: yes
  ignore_errors: yes

- name: Xxx
  ansible.builtin.shell: |
    set -o pipefail
    ls -ld /run
    ls -l /run
    journalctl -xe | grep chrony
    systemctl status {{ chrony_service }}
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false
  register: xxx

- name: Xxx
  ansible.builtin.debug:
    var: xxx
