---

- name: Install chrony
  ansible.builtin.package:
    name: "{{ chrony_packages }}"
    state: present

- name: Start chrony  # noqa ignore-errors
  ansible.builtin.service:
    name: "{{ chrony_service }}"
    state: started
    enabled: yes
