---

- name: Install chrony
  ansible.builtin.package:
    name: "{{ chrony_packages }}"
    state: present

- name: Make chrony work with docker
  when:
    - ansible_facts.distribution == 'Ubuntu' and ansible_facts.distribution_major_version == "26"
    - ansible_facts.virtualization_type in [ 'docker', 'container', 'containerd' ]
  block:

    - name: Create /etc/systemd/system/chrony.service.d
      ansible.builtin.file:
        path: /etc/systemd/system/chrony.service.d
        state: directory
        mode: "0644"

    - name: Create chrony overwrite
      ansible.builtin.copy:
        content: |
          [Unit]
          ConditionPathExists=
          ConditionCapability=
        dest: /etc/systemd/system/chrony.service.d/override.conf
        mode: "0644"
      notify: Restart chrony

- name: Start chrony
  ansible.builtin.systemd:
    name: "{{ chrony_service }}"
    state: started
    enabled: yes
    daemon_reload: true
