---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - '{{ ansible_distribution }}.yml'
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: Install chrony
  package:
    name: "{{ chrony_packages }}"
    state: present

- name: Configure chrony
  template:
    src: "{{ chrony_conf_template }}"
    dest: "{{ chrony_conf }}"
    mode: '0644'
  register: chrony_conf

- name: Start chrony
  service:
    name: chronyd
    state: started
    enabled: yes
  register: _chrony_start
  tags:
    - molecule-notest

- name: Restart chrony
  service:
    name: chronyd
    state: restarted
  when: not _chrony_start.changed and chrony_conf.changed
  tags:
    - molecule-notest
   
- name: Synchronize clock  # noqa no-handler
  command: chronyc -a makestep
  when:
    - chrony_conf.changed|bool
  tags:
    - molecule-notest
