---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Install chrony
  ansible.builtin.include_tasks: install.yml

- name: Configure chrony
  ansible.builtin.include_tasks: config.yml

- name: Synchronize clock  # noqa no-handler
  ansible.builtin.command:
    cmd: chronyc -a makestep
  changed_when: false
  tags:
    - molecule-notest
